"use strict";
module.exports = {
  config: {
    updateChannel: "stable",
    fontSize: 10,
    fontFamily:
      '"FiraCode Nerd Font", "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: "normal",
    fontWeightBold: "bold",
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: "#5c6370",
    cursorAccentColor: "#000",
    cursorShape: "BEAM",
    cursorBlink: true,
    foregroundColor: "#c3c7d1",
    backgroundColor: "#161925",
    selectionColor: "#828997",
    borderColor: "#333",
    css: `
      .term_fit > .terminal {
        display: flex;
        align-items: center;
        justify-content: center;
      }   `,
    termCSS: "",
    workingDirectory: "",
    showHamburgerMenu: false,
    showWindowControls: false,
    padding: "0",
    colors: {
      black: "#282c34",
      red: "#ed254e",
      green: "#71f79f",
      yellow: "#f9dc5c",
      blue: "#7cb7ff",
      magenta: "#c74ded",
      cyan: "#00c1e4",
      white: "#dcdfe4",
      lightBlack: "#282c34",
      lightRed: "#ed254e",
      lightGreen: "#71f79f",
      lightYellow: "#f9dc5c",
      lightBlue: "#7cb7ff",
      lightMagenta: "#c74ded",
      lightCyan: "#00c1e4",
      lightWhite: "#dcdfe4",
      limeGreen: "#32CD32",
      lightCoral: "#F08080",
    },
    shell: "/usr/bin/tmux",
    shellArgs: ["new", "-As0"],
    env: {},
    bell: false,
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: "vertical",
    webGLRenderer: true,
    webLinksActivationKey: "alt",
    disableLigatures: true,
    disableAutoUpdates: false,
    screenReaderMode: false,
    preserveCWD: true,
  },
  plugins: [
    "hyper-search",
    "hyper-transparent",
    "hyper-dark-scrollbar",
    "hyperminimal",
  ],
  localPlugins: [],
  keymaps: {},
  hyperTransparent: { opacity: 0.8, vibrancy: "ultra-dark" },
};
