# hide OSC when paused
showonpause=false

nibbles_style=triangle

# colors
windowcontrols_close_hover=#f38ba8
windowcontrols_max_hover=#cba6f7
windowcontrols_min_hover=#74c7ec
seekbarfg_color=#b4befe
hover_effect_color=#b4befe
seek_handle_color=#89b4fa
seek_handle_border_color=#89b4fa
seekbarbg_color=#585b70
seekbar_cache_color=#9399b2
nibble_color=#f5c2e7
nibble_current_color=#cdd6f4
