#!/usr/bin/env python3

import json
import os
import re


def mapWindow(w):
    return "{}\\0icon\\x1f{}".format(
        "%s (%s_%s)" % (w["title"], w["address"], w["workspace"]["id"]),
        w["initialClass"].lower(),
    )


windows = json.loads(os.popen("hyprctl -j clients").read())
filtered_windows = list(filter(lambda w: w["workspace"]["id"] != -1, windows))
mapped_windows = list(map(mapWindow, filtered_windows))


selected_window = os.popen(
    'echo -en "%s" | fuzzel --dmenu' % ("\n".join(mapped_windows))
).read()

print("selected_window: %s" % (selected_window))

if selected_window:
    match = re.search(r"\((\w+)\)$", selected_window)
    addr = match.group(1).split("_")[0]
    os.system("hyprctl dispatch focuswindow address:%s" % (addr))
else:
    print("no selected_window")
