[colors.bright]
black = "#282c34"
blue = "#7cb7ff"
cyan = "#00c1e4"
green = "#71f79f"
magenta = "#c74ded"
red = "#ed254e"
white = "#dcdfe4"
yellow = "#f9dc5c"

[colors.normal]
black = "#282c34"
blue = "#7cb7ff"
cyan = "#00c1e4"
green = "#71f79f"
magenta = "#c74ded"
red = "#ed254e"
white = "#dcdfe4"
yellow = "#f9dc5c"

[colors.primary]
background = "#161925"
bright_foreground = "#828997"
dim_foreground = "#5c6370"
foreground = "#c3c7d1"
